# Generated by Django 3.0 on 2020-07-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aboutcontents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutContents',
            new_name='AboutContent',
        ),
    ]
